### ISSUE TITLE
Create New Vena Report:  CEAB Attribute Results

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#177] opened 2018-09-06 20:16 UTC
![image](https://user-images.githubusercontent.com/38359810/45182742-2a9d0100-b1f0-11e8-9a76-9cc236e13ab9.png)

**Comment by smiths** [comment] 2018-09-07 04:58
@arana2, if we need to, we can set up a meeting with Jake to discuss how this chart was calculated.

**Comment by arana2** [comment] 2018-09-11 15:07
Thanks, @smiths.  I think I have an idea of how the chart is being generated.

**CEAB Attribute Report Requirements**
1.  Create a custom combo chart that can be generated based on the rubric data in Vena
i)  X-axis will be the attributes
ii) Y-axis will contain the results (Below, Marginal, Meets, Exceeds) where the total of the 4 expectations will equal 100%.  Values entered will be converted into %.
iii) Avg Score: will be represented by a line graph.  it will plot a point on the average score of the expectation (BE = 1; MA = 2; ME = 3; EE = 4;) for each attribute

2.  User Input
i) Able to select by program or course
ii) Able to select by Year, Term, or all years
iii) Able to select by section or all sections

**Comment by arana2** [comment] 2018-09-11 19:18
Hi @smiths,

I am able to replicate the CEAB Attribute Report shared by Jake.  The development report is located in Vena under: Manager -> Files Library -> Reports -> WIP – CEAB Attribute Report -> CEAB Attribute Report v2.xlsm.

If you are satisfied with the report, please let me know and I will deploy it to our production environment.

The report is compatible for Windows users.  Initially, the Mac version was working, but it is currently displaying a connection issue between the Vena Contributor Connector and Vena database.  This is not an isolated issue since I am experiencing the same defect with the Mac version of Rubric Input Template as well.  I will create a separate Git issue and follow up with the Vena Team.
[Testing CEAB Attribute Report.docx](https://github.com/smiths/MEASURE/files/2372364/Testing.CEAB.Attribute.Report.docx)

The user is able to generate the report by configuring the following:
i)	Choosing a Program OR Course
ii)	Choosing a Term OR a Year OR ALL Years
iii)	Choosing a Section or ALL Sections

Course:   TEST 101; Year 2017-2018 Term 2; Section: 1
![image](https://user-images.githubusercontent.com/38359810/45382307-c99d7080-b5d5-11e8-891c-845dbe7403a7.png)

Reference: Rubric Input Template
![image](https://user-images.githubusercontent.com/38359810/45382324-d91cb980-b5d5-11e8-89f9-bbd5baadbd52.png)

Program: Integrated Biomedical Enginering & Health Sciences; 2017-2018; Section ALL
![image](https://user-images.githubusercontent.com/38359810/45381837-7a0a7500-b5d4-11e8-85d0-fdedda5eb944.png)

Reference: Rubric Input Template
![image](https://user-images.githubusercontent.com/38359810/45382348-e5a11200-b5d5-11e8-818e-14a7b5faf485.png)

**Comment by smiths** [comment] 2018-09-11 20:38
Excellent!  This is exactly the kind of work we need to show off!  😄 What happens when you run it for Chemical Engineering?  Does it look at all like Jake's data, or is there not enough data in Vena for it to work properly?  I think Jake may have had access to data that is not currently in the Vena system.

Too bad about the Mac issue, but it sounds like the problem is on Vena's end.  Yes, please proceed with issuing a ticket to them.

I am interested in the answer to the chemical engineering question I asked above, but please do not let that stop you from adding this report to the production environment.

It seems to me that departments could use this report to complete the summary report that Ken is requesting.  Am I correct that if a department has their course data entered they can generate this figure?  If that is the case, we should inform Ken and Maria of this and send a brief blurb with instructions on how to generate the figure.

**Comment by smiths** [comment] 2018-09-12 21:05
@arana2 this is great!  I think at this point the emphasis will be on generating nice pictures automatically, which you can now do.  The quality of the data is a separate issue that we can't really take on.  If chemical engineering wants to sort that out, that is an issue for them.  Having said that, we should still inform Jake of the difference.  Would you like to write him, with a CC to me, or would you like me to write him, with a CC to you?

With the current discussion going on about the summary report I think this is a great opportunity to show the value of MEASURE.  Maria and Ken will definitely be interested in distributing the instructions for generating this report.  

If there is anything I can do to help, please let me know.  Hopefully you can tell that I'm very excited about this report.  I don't want to get ahead of myself, but it feels like some of the promise of MEASURE is finally coming to fruition.  😄

**Comment by arana2** [comment] 2018-09-13 14:53
Hi @smiths,

If it is okay with you, may I inform Jake and CC you on the email?  I would like to get my name out there for everyone as the main point of contact for MEASURE.  That way, I can help reduce your workload :)

I agree.  I am starting to feel more confident with showing off Vena's capabilities,  *Crossing fingers* :)

**Comment by smiths** [comment] 2018-09-13 15:08
That is my preference too!  Yes, please inform Jake of the discrepancy.

**Comment by arana2** [comment] 2018-09-21 18:04
Hi @smiths,

I am not sure if you had a chance to generate the report, but I think this ticket can be closed.

Windows and Mac users are now able to generate the CEAB Attribute Report as long as Rubric data is entered in Vena.

Let me know what you think.

Thanks,
Andrew

**Comment by smiths** [comment] 2018-09-21 20:16
@arana2, before closing the issue, I have one quick question.  I went through the steps for a Mac and it worked really well, except the items in the Program list surprised me a bit.  I specified the Program,  Year and Section as requested before generating/saving the report.  The program options include the entries I expected, like Level II Software Engineering, but Program also include individual courses.  Is that by design?  It makes the interface a bit cumbersome to have all of these options.  Maybe this is specific to the Mac interface.  I did not test with the Windows interface.

**Comment by arana2** [comment] 2018-09-25 14:46
Hi @smiths, 
Thank you for your feedback.

If I understand correctly, you are referring to the items in the Program dropdown list.

**Windows Environment**
![image](https://user-images.githubusercontent.com/38359810/46020725-04f76f00-c0ad-11e8-9714-df5c016d36a9.png)

**Mac Environment**
![image](https://user-images.githubusercontent.com/38359810/46021317-7126a280-c0ae-11e8-98e4-37060702217d.png)

If so, yes this was by design.  My idea was to provide users the ability to generate the CEAB Attribute Report by All Programs, Program, Program Level, or Course.  This would enable users with greater flexibility when generating the report.

Unfortunately, the Mac and Windows environment retrieve and display the items (programs) and sub-items (courses) differently.  It would be great if the Mac environment can mimic the way Windows displays the programs and courses.  I can raise this item with Vena to get a better understanding.

In the meantime, I can update the dropdown to only display the Program to make it less cumbersome.

Please let me know your thoughts.

**Comment by smiths** [comment] 2018-09-25 16:55
@arana2, you are correct about my question.  It is the program dropdown list that I was interested in.  I agree with you that is nice to have flexibility.  The only problem is how many items are listed and the fact that they aren't sorted in a logical way.  There is some sort behind it (alphabetical?), but it took a bit of scrolling to get to the items I was interested in.

I say for now that you leave it as you have it.  Once we get to a proper stakeholders meeting, we can start asking them questions that will help make issues like this clear.  If you have a file where you are recording ideas to discuss with the stakeholders, this might be a good item to add to that file.

As far as the original issue goes, you have sorted it out, and it can be closed.

**Closed by smiths** 2018-09-25 16:55 UTC
Labels: Enhancement

**Comment by arana2** [comment] 2018-09-26 14:09
Thanks for the feedback.  I will add this to the requirements document.
