### ISSUE TITLE
Errors in Formula References

### ISSUE THREAD

**Issue by JoeSpan** [smiths/MEASURE#100] opened 2016-11-18 15:16 UTC
So some of the formulas are not working. This seems to be a sporadic issue as I have had different courses work. This is Mech Eng 2P04 2015-2016 Term 1. The graphs are not showing up. 

It seems to be something with the detailed chart option. when you click the details tab, only the summary chart is generated. 
@smiths 

![image](https://cloud.githubusercontent.com/assets/20819724/20434954/25ce5dbe-ad78-11e6-9f59-b7c9db368458.png)

**Comment by smiths** [comment] 2016-11-18 18:29
@EvanVena , I have reproduced the same error as Joe on my machine with Excel 2013.  Do you know what is going on here?

**Comment by EvanVena** [comment] 2016-11-21 20:14
@JoeSpan @smiths 
Not sure, if this just temporary server issue or not,
it seems fine on my side now, can you please check again?
![image](https://cloud.githubusercontent.com/assets/20912011/20498952/41ddef4c-affd-11e6-8fce-5c1e77165143.png)

**Comment by JoeSpan** [comment] 2016-11-21 22:12
@EvanVena  It does not seem to be temporary I still get the same error
![image](https://cloud.githubusercontent.com/assets/20819724/20502776/ac7d931a-b00d-11e6-81a2-38e018739ab9.png)

**Comment by smiths** [comment] 2016-11-22 04:33
I just tested this again.  Initially I received the same output as I previously had, which was the same output the @JoeSpan shows above.  However, when I scrolled down, the spreadsheet suddenly improved.  It now looks like what @EvanVena attached above.  I didn't do anything, except scroll down.  However, I wonder if the fix was caused by a recent update the the Vena tab tool?  It was updated on my machine in the last few minutes.

@JoeSpan , what happens if you update the Vena add-in tool for Excel?  Instructions can be found on the web-page: http://measure.mcmaster.ca/

You need to quit Excel before upgrading.

**Comment by JoeSpan** [comment] 2016-11-22 15:34
So I still get the error, but after accepting the error's existence, the graphs load fine. I did notice that indicator 1.4 showed all 4 bars as 100% where the others were blank. I went into the course input template and noticed that something is different with the formula. Here the formula cell has a green check in the upper corner only on indicator 1.4 but does not happen on the rest.  This could be what is generating our error. @EvanVena Do you know why this could have happened? @smiths 
![image](https://cloud.githubusercontent.com/assets/20819724/20529658/f4c1394c-b09e-11e6-9bd2-0dff9cc0068c.png)

**Comment by EvanVena** [comment] 2016-12-16 15:13
@JoeSpan  can you confirm if this issue still there?

**Comment by smiths** [comment] 2017-01-02 22:05
Joe did not reply, and is now out of this project.  I'll close the issue, with the hope that it does not come up again.  :-)

**Closed by smiths** 2017-01-02 22:05 UTC
